[project]
name = "ds"
version = "0.3.2"
description = "A collection of data structures, just for fun and for practice"
authors = [{name = "guito"}]
license = "MIT"
dependencies = ["pytest"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"